export interface RoundStats {
  score: number
  scoreToPar: number
  birdies: number
  pars: number
  bogeys: number
  doubleBogeys: number
  triplePlus: number

  putts: number
  puttsPerHole: number
  onePutts: number
  threePutts: number

  fairwaysHit: number
  fairwayPercentage: number

  gir: number
  girPercentage: number

  upAndDowns: number

  penalties: number

  longestDrive: number
  longestPutt: number

  strokesGained: {
    total: number
    putting: number
  }

  totalDistanceWalked?: number // TODO implement this
}

export interface OverallStats {
  sample: SampleInfo

  scoring: ScoringStats
  putting: PuttingStats
  driving: DrivingStats
  approach: ApproachStats
  shortGame: ShortGameStats
  tendencies: Tendencies
  strokesGained: StrokesGainedStats

  equipment: EquipmentBreakdown
}

export interface SampleInfo {
  rounds: number
  holes: number
  putts: number
  fullShots: number
}

export interface ScoringStats {
  avgScore: number
  avgToPar: number

  birdieRate: number
  parRate: number
  bogeyRate: number
  doublePlusRate: number
}

export interface PuttingStats {
  avgPuttsPerHole: number
  onePuttRate: number
  threePuttRate: number

  makeRatesByDistance: DistanceMakeRate[]
  leaveDistanceByDistance: DistanceLeaveStats[]

  missBias: MissBiasStats
  greenReading: GreenReadingStats

  lagPutting: LagPuttingStats
}

export interface DistanceMakeRate {
  distanceBucket: string // "0-3ft", "3-6ft", etc
  attempts: number
  makeRate: number
}

export interface DistanceLeaveStats {
  distanceBucket: string
  avgLeaveDistance: number
}

export interface MissBiasStats {
  leftMissPct: number
  rightMissPct: number
  longMissPct: number
  shortMissPct: number
}

export interface GreenReadingStats {
  correctReadPct: number
  underReadPct: number
  overReadPct: number
}

export interface LagPuttingStats {
  attemptsOver20ft: number
  threePuttAvoidanceRate: number
  avgLeaveDistance: number
}

export interface DrivingStats {
  fairwayHitRate: number
  avgDistance: number
  distanceStdDev: number

  missPattern: {
    leftPct: number
    rightPct: number
  }
}

export interface ApproachStats {
  girRate: number

  proximityByDistance: ProximityBucket[]
  missPattern: {
    shortPct: number
    longPct: number
    leftPct: number
    rightPct: number
  }
}

export interface ProximityBucket {
  distanceBucket: string // 50-100, 100-150, etc
  avgProximity: number
}

export interface ShortGameStats {
  upAndDownRate: number
  proximityFromInside50: number
}

// Formatted text describing the player's tendencies, generated by prompting GPT-4 or similar with the raw stats.
export interface Tendencies {
  commonMiss: string
  puttingTendency: string
  drivingTendency: string
}

export interface StrokesGainedStats {
  total: number
  putting: number
  offTee: number
  approach: number
  aroundGreen: number
}

export interface EquipmentBreakdown {
  byPutter: Record<string, PuttingStats>
  byGrip: Record<string, PuttingStats>
}